name: mobile_labs
description: Dealeska mobile labs project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase: ^9.0.2
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.8
  firebase_auth: ^3.3.7
  google_maps_flutter: ^2.1.1
  weather: ^2.0.1
  search_choices: ^2.0.17
  path_provider: ^2.0.9
  json_serializable: ^6.1.4
  json_annotation: ^4.4.0
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  #build_runner: ^2.1.7
  #flutter_lints: ^1.0.0

flutter:  
  uses-material-design: true   
  assets:   
    - assets/